**INSTRUCTIONS:**

Go to File -> Save a Copy in Drive and edit this notebook in your copy

 Put all your doubts on Discord channel

Do not plagiarise


In [ ]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
print(np.ones_like(x))

[1 1 1 1]


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
 X = np.array([[1, 2], [3, 4]])
 print(np.matrix(X))

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
print(np.linspace(3,10,50))

[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x=np.array([[1, 2, 3], [4, 5, 6]])
print(np.ravel(np.transpose(x)))

[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.arange(1,10)
print(np.split(x,[4,6]))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x=np.array([[1,2],[3,4]])
print(np.linalg.inv(x))
print(np.trace(x))

[[-2.   1. ]
 [ 1.5 -0.5]]
5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
x=np.array([[1,4],[3,1]])
print(np.sort(x,axis=1))


[[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
x=np.array([[1,4],[3,1]])
print(np.argsort(x, axis=1))

[[0 1]
 [1 0]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x=np.random.rand(2,5)*10
print(x)
print("maxs:",np.amax(x,axis=1))
print(np.argmax(x,axis=1))
print("mins:",np.amin(x,axis=1))
print(np.argmin(x,axis=1))


[[4.11962568 5.7715844  4.95260634 1.69334972 7.79838848]
 [6.28545424 7.1233005  6.96742871 6.05648603 3.38213043]]
maxs: [7.79838848 7.1233005 ]
[4 1]
mins: [1.69334972 3.38213043]
[3 4]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value.

In [ ]:
iris_2d=iris_2d[~np.isnan(iris_2d).any(axis=1)]
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Find the correlation between first two columns.

In [ ]:
print(np.corrcoef(iris_2d[:,0],iris_2d[:,1]))


[[ 1.         -0.10936925]
 [-0.10936925  1.        ]]


Find the mean,median and standard deviation of column 3.

In [ ]:
print("mean",np.mean(iris_2d[:,2]))
print("median",np.median(iris_2d[:,2]))
print("standard deviation",np.std(iris_2d[:,2]))

mean 3.758666666666666
median 4.35
standard deviation 1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
iris_2d=np.column_stack((iris_2d,(np.pi*iris_2d[:,2]*iris_2d[:,0]**2)/3))
print(iris_2d)

[[  5.1          3.5          1.4        ...  38.13265163  38.13265163
   38.13265163]
 [  4.9          3.           1.4        ...  35.20049849  35.20049849
   35.20049849]
 [  4.7          3.2          1.3        ...  30.07237208  30.07237208
   30.07237208]
 ...
 [  6.5          3.           5.2        ... 230.069302   230.069302
  230.069302  ]
 [  6.2          3.4          5.4        ... 217.37307889 217.37307889
  217.37307889]
 [  5.9          3.           5.1        ... 185.91002846 185.91002846
  185.91002846]]


Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [ ]:

unique_species, counts = np.unique( iris[:, 4], return_counts=True)
print("Count of Unique Species:")
for species, count in zip(unique_species, counts):
    print(species.decode('utf-8'), ":", count)

Count of Unique Species:
Iris-setosa : 50
Iris-versicolor : 50
Iris-virginica : 50


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [ ]:
petal_length = iris_2d[:, 2].astype(float)

bin_edges = [0, 3, 5, np.inf]
bin_labels = ['small', 'medium', 'large']

binned_petal_length = np.digitize(petal_length, bin_edges, right=True)

text_array = np.array(bin_labels)[binned_petal_length - 1]

print(text_array)

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'small' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'medium' 'large' 'large' 'large' 

Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:

print( np.bincount(iris_2d[:, 2].astype(int)).argmax())

1
